### ISSUE TITLE
taks 1 handle the following conversion:

### ISSUE THREAD

**Issue by deibyocampo** [deibyocampo/printf#2]
* [x] %d 
* [x] %i 
* [x] note *:  must be accept negative

**Comment by student369** [comment]
Hi @deibyocampo , in this moment the printf function works with numbers with the last push to the develop branch, it's pending to re-factorize to pass the codification standard.

**Comment by student369** [comment]
Hi @deibyocampo , I pushed the last version of _printf function to the develop branch accepting betty style.
